export const FETCH_USER = "FETCH_USER";
export const USER_UPDATE = "USER_UPDATE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";
export const BOOKS_FETCH_FAIL = "BOOKS_FETCH_FAIL";
export const BOOKS_FETCH_REQUEST = "BOOKS_FETCH_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";
export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";
export const BOOK_DELETE_REQUEST = "BOOK_DELETE_REQUEST";

export const BOOKS_SEARCH_UPDATE = "BOOKS_SEARCH_UPDATE";
export const BOOKS_PROFILE_FETCH_SUCCESS = "BOOKS_PROFILE_FETCH_SUCCESS";
export const BOOKS_SORT_BY = "BOOKS_SORT_BY";
export const SETTINGS_CHANGE_PHONE = "SETTINGS_CHANGE_PHONE";
export const SETTINGS_CHANGE_MESSENGER_NAME = "SETTINGS_CHANGE_MESSENGER_NAME";
